ава готово
js-tasks-ru/htmlcss-20230911-4_elmir-kuba pull request #19
Opened 2023-10-09 08:45 UTC by ElmirKuba

2023-10-09 08:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-10 19:23 UTC, GSemikozov requested changes

2023-10-10 19:23 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__inner {
этот хак не надо применять, у нас просто 102x102

2023-10-11 20:35 UTC, GSemikozov requested changes

2023-10-11 20:35 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__inner {
и все-таки это лишний элемент, стили отсюда унесем на уровень блока

2023-10-23 12:54 UTC, GSemikozov approved these changes

2023-10-23 12:54 UTC, merged