05 lection3  template mobile
js-tasks-ru/htmlcss-20230911-4_elmir-kuba pull request #22
Opened 2023-10-09 11:38 UTC by ElmirKuba

2023-10-09 11:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-10 19:28 UTC, GSemikozov requested changes

2023-10-10 19:28 UTC, GSemikozov commented on components/component-content/component-content.css
> +    background-color: #FFF;
background-color + filter не меняются, нет смысла здесь дублировать

2023-10-10 19:28 UTC, GSemikozov commented on components/component-content/component-content.css
> +    grid-template-rows: auto 1fr;
и это

2023-10-10 19:28 UTC, GSemikozov commented on components/component-content/component-content.css
> +    grid-template-rows: auto 1fr;
39-41

2023-10-10 19:28 UTC, GSemikozov commented on components/component-content/component-content.css
> +    font-style: normal;
и здесь не надо дублировать то что не меняется

2023-10-10 19:28 UTC, GSemikozov commented on components/main/main.css
> +.main__component-page {
предполагался видимо модификатор а не элемент?

2023-10-10 19:28 UTC, GSemikozov commented on pages/template.html
> +              <div class="container container__component-page">
тоже модификатор?

2023-10-10 19:28 UTC, GSemikozov commented on pages/template.html
> +            <footer class="footer footer__component-page">
и тут

2023-10-10 19:28 UTC, GSemikozov commented on pages/template.html
> +            <main class="main main__component-page">
модификатор?

2023-10-11 11:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-11 11:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-11 11:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-11 11:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-12 08:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-23 05:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-23 05:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-23 06:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-23 06:35 UTC, ElmirKuba commented on components/component-content/component-content.css
> +    background-color: #FFF;
исправил

2023-10-23 06:36 UTC, ElmirKuba commented on components/component-content/component-content.css
> +    grid-template-rows: auto 1fr;
исправил, а что такое 39-41 не совсем понял

2023-10-23 06:39 UTC, ElmirKuba commented on components/component-content/component-content.css
> +    font-style: normal;
исправил, просто я не думаю лишний раз а нажимаю в фигме скопировать стили и все:)

2023-10-23 06:40 UTC, ElmirKuba commented on components/main/main.css
> +.main__component-page {
Да, вы правы, исправил

2023-10-23 06:40 UTC, ElmirKuba commented on pages/template.html
> +              <div class="container container__component-page">
Да, исправил, спасибо за замечание

2023-10-23 06:43 UTC, ElmirKuba commented on pages/template.html
> +            <footer class="footer footer__component-page">
Исправлено

2023-10-23 06:43 UTC, ElmirKuba commented on pages/template.html
> +            <main class="main main__component-page">
Исправлено

2023-10-23 06:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-23 13:02 UTC, GSemikozov commented on components/component-content/component-content.css
> +    grid-template-rows: auto 1fr;
это строки кода)

2023-10-23 13:03 UTC, GSemikozov requested changes
конфликты

2023-10-24 04:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-24 04:37 UTC, ElmirKuba commented
Здравстуйте. Исправил конфликты.

2023-10-24 04:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-24 04:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-25 18:38 UTC, GSemikozov approved these changes

2023-10-25 18:38 UTC, merged