done
js-tasks-ru/htmlcss-20230911-4_elmir-kuba pull request #5
Opened 2023-09-19 15:26 UTC by ElmirKuba

2023-09-19 19:54 UTC, GSemikozov requested changes

2023-09-19 19:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.wrapper  {
другой блок в файле стилей блока под названием button? ошибка, удалим ненужные врапперы

2023-09-19 19:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.wrapper  {
если хочется добавить враппер на странице превью / решения - это можно сделать в отдельном файле который подключаем лишь здесь

2023-09-19 19:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  opacity: 0.5;
и еще pointer-events: none

2023-09-20 03:32 UTC, ElmirKuba commented on 03-lection1/01-button/button.css
> +.wrapper  {
/исправлено

2023-09-20 03:34 UTC, ElmirKuba commented on 03-lection1/01-button/button.css
> +  opacity: 0.5;
/исправлено

2023-09-20 03:35 UTC, ElmirKuba commented
исправлено

2023-09-20 19:53 UTC, GSemikozov approved these changes

2023-09-20 19:53 UTC, merged