Главная страница теперь с использованием flex официально разрешена, п…
js-tasks-ru/htmlcss-20230911-4_elmir-kuba pull request #7
Opened 2023-09-23 12:32 UTC by ElmirKuba

…ереписал ее, придерживаясь не использовать container

2023-09-23 12:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-23 13:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-24 22:29 UTC, GSemikozov requested changes

2023-09-24 22:29 UTC, GSemikozov commented on components/main/main.css
> +.main__button {
нельзя вот таким вот образом из другого компонента менять внутреннюю реализацию кнопки - это лишнее здесь

2023-09-25 06:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-25 07:58 UTC, GSemikozov approved these changes

2023-09-25 07:58 UTC, merged