finish skeleton
js-tasks-ru/htmlcss-20230911-4_elmir-kuba pull request #8
Opened 2023-09-25 07:26 UTC by ElmirKuba

2023-09-25 08:01 UTC, GSemikozov requested changes

2023-09-25 08:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title-1 {
очень неинформативные модификаторы) имена модификаторов должны описывать что. /как они модифицируют, например .skeleton__title_short, поскольку речь о ширине / длине

2023-09-25 08:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
ширину в процентах

2023-09-25 08:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  height: 20px;
высоту на уровне общего класса элемента .skeleton__title

2023-09-25 08:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title-1 {
и по структуре выходит это даже элементы.. в общем, должны быть модификаторы ширину у элемента .skeleton__title

2023-09-25 08:25 UTC, ElmirKuba commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title-1 {
> и по структуре выходит это даже элементы.. в общем, должны быть модификаторы ширину у элемента .skeleton__title

испр

2023-09-25 08:25 UTC, ElmirKuba commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
> ширину в процентах

исп

2023-09-25 08:26 UTC, ElmirKuba commented on 04-lection2/02-skeleton/skeleton.css
> +  height: 20px;
> высоту на уровне общего класса элемента .skeleton__title

испр

2023-09-25 21:06 UTC, GSemikozov requested changes

2023-09-25 21:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title {
.skeleton__title = .skeleton__content-item, может тогда .skeleton__line?

2023-09-25 21:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 515px;
в процентах

2023-09-26 15:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-27 20:50 UTC, GSemikozov requested changes

2023-09-27 20:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title {
.skeleton__title и .skeleton__content-item одно и то же ведь

2023-09-28 21:02 UTC, GSemikozov requested changes

2023-09-28 21:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton copy.css
> +.skeleton__title {
.skeleton__title = .skeleton__content-item

2023-09-28 21:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                            <div class="skeleton__line skeleton__line_title-33percent"></div>
skeleton__line_title-33percent - это откуда?)

2023-09-28 21:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                            <div class="skeleton__line skeleton__line_title-49percent"></div>
skeleton__line_title-49percent и это

2023-09-28 21:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton copy.css
> +.skeleton {
копия?

2023-09-28 21:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton {
и еще разок?)

2023-09-29 05:16 UTC, ElmirKuba commented
все удалил

2023-09-29 10:20 UTC, ElmirKuba commented
вернул пока полоски без модификаторов

2023-10-01 12:07 UTC, GSemikozov requested changes

2023-10-01 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 579px;
зачем фиксируем ширину? не стоит.

2023-10-01 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  height: fit-content;
лишнее (так будет по умолчанию)

2023-10-01 19:11 UTC, GSemikozov requested changes

2023-10-01 19:11 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__content_title-short {
все еще не исправлено) .skeleton__content_short и тд

2023-10-02 19:27 UTC, GSemikozov approved these changes

2023-10-02 19:28 UTC, merged